// <auto-generated />
using System;
using HMI.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HMI.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("HMI.Platform.Core.Models.Alarm", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClearedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClearedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SensorId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VesselId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Severity");

                    b.HasIndex("Status");

                    b.HasIndex("TriggeredAt");

                    b.HasIndex("VesselId");

                    b.ToTable("Alarms");
                });

            modelBuilder.Entity("HMI.Platform.Core.Models.Engine", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("FuelConsumption")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRPM")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("OilPressure")
                        .HasColumnType("REAL");

                    b.Property<int>("RPM")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VesselId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("VesselId");

                    b.ToTable("Engines");

                    b.HasData(
                        new
                        {
                            Id = "engine-001",
                            FuelConsumption = 12.5,
                            IsRunning = true,
                            LastUpdated = new DateTime(2025, 11, 6, 14, 6, 12, 903, DateTimeKind.Utc).AddTicks(4972),
                            MaxRPM = 1800,
                            Name = "Main Engine Port",
                            OilPressure = 0.0,
                            RPM = 1200,
                            Status = 2,
                            Temperature = 85.5,
                            Type = "Diesel",
                            VesselId = "vessel-001"
                        },
                        new
                        {
                            Id = "engine-002",
                            FuelConsumption = 12.800000000000001,
                            IsRunning = true,
                            LastUpdated = new DateTime(2025, 11, 6, 14, 6, 12, 903, DateTimeKind.Utc).AddTicks(4977),
                            MaxRPM = 1800,
                            Name = "Main Engine Starboard",
                            OilPressure = 0.0,
                            RPM = 1180,
                            Status = 2,
                            Temperature = 87.200000000000003,
                            Type = "Diesel",
                            VesselId = "vessel-001"
                        },
                        new
                        {
                            Id = "engine-003",
                            FuelConsumption = 0.0,
                            IsRunning = false,
                            LastUpdated = new DateTime(2025, 11, 6, 14, 6, 12, 903, DateTimeKind.Utc).AddTicks(4979),
                            MaxRPM = 1600,
                            Name = "Main Engine",
                            OilPressure = 0.0,
                            RPM = 0,
                            Status = 0,
                            Temperature = 25.0,
                            Type = "Diesel",
                            VesselId = "vessel-002"
                        });
                });

            modelBuilder.Entity("HMI.Platform.Core.Models.MessageBusEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("Source");

                    b.HasIndex("Timestamp");

                    b.ToTable("MessageBusEvents");
                });

            modelBuilder.Entity("HMI.Platform.Core.Models.Sensor", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxValue")
                        .HasColumnType("REAL");

                    b.Property<double>("MinValue")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Type");

                    b.ToTable("Sensors");

                    b.HasData(
                        new
                        {
                            Id = "sensor-001",
                            IsActive = true,
                            LastUpdated = new DateTime(2025, 11, 6, 14, 6, 12, 903, DateTimeKind.Utc).AddTicks(4999),
                            MaxValue = 120.0,
                            MinValue = 0.0,
                            Name = "Engine Temperature Sensor 1",
                            Type = "Temperature",
                            Unit = "Celsius",
                            Value = 85.5
                        },
                        new
                        {
                            Id = "sensor-002",
                            IsActive = true,
                            LastUpdated = new DateTime(2025, 11, 6, 14, 6, 12, 903, DateTimeKind.Utc).AddTicks(5002),
                            MaxValue = 10.0,
                            MinValue = 0.0,
                            Name = "Engine Pressure Sensor 1",
                            Type = "Pressure",
                            Unit = "Bar",
                            Value = 2.5
                        },
                        new
                        {
                            Id = "sensor-003",
                            IsActive = true,
                            LastUpdated = new DateTime(2025, 11, 6, 14, 6, 12, 903, DateTimeKind.Utc).AddTicks(5004),
                            MaxValue = 50.0,
                            MinValue = 0.0,
                            Name = "Fuel Flow Sensor 1",
                            Type = "Flow",
                            Unit = "L/min",
                            Value = 12.5
                        });
                });

            modelBuilder.Entity("HMI.Platform.Core.Models.Vessel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxSpeed")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Vessels");

                    b.HasData(
                        new
                        {
                            Id = "vessel-001",
                            CreatedAt = new DateTime(2025, 11, 6, 14, 6, 12, 903, DateTimeKind.Utc).AddTicks(4886),
                            LastUpdated = new DateTime(2025, 11, 6, 14, 6, 12, 903, DateTimeKind.Utc).AddTicks(4882),
                            Length = 300.0,
                            Location = "Port of Rotterdam",
                            MaxSpeed = 24.5,
                            Name = "MV Atlantic Explorer",
                            Status = 1,
                            Type = "Container Ship",
                            Width = 45.0
                        },
                        new
                        {
                            Id = "vessel-002",
                            CreatedAt = new DateTime(2025, 11, 6, 14, 6, 12, 903, DateTimeKind.Utc).AddTicks(4889),
                            LastUpdated = new DateTime(2025, 11, 6, 14, 6, 12, 903, DateTimeKind.Utc).AddTicks(4887),
                            Length = 280.0,
                            Location = "Port of Singapore",
                            MaxSpeed = 22.0,
                            Name = "MV Pacific Navigator",
                            Status = 1,
                            Type = "Bulk Carrier",
                            Width = 42.0
                        });
                });

            modelBuilder.Entity("HMI.Platform.Core.Models.Engine", b =>
                {
                    b.HasOne("HMI.Platform.Core.Models.Vessel", null)
                        .WithMany("Engines")
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HMI.Platform.Core.Models.Vessel", b =>
                {
                    b.Navigation("Engines");
                });
#pragma warning restore 612, 618
        }
    }
}
